---
abstract: 'Perl interface to the ISAAC PRNG algorithm'
author:
  - 'Jonathan Yu <jawnsy@cpan.org>'
build_requires:
  Test::NoWarnings: 0.084
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.101670'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Random-ISAAC
requires:
  Math::Random::ISAAC::XS: 0
  Test::More: 0.62
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Math-Random-ISAAC
  homepage: http://search.cpan.org/dist/Math-Random-ISAAC
  repository: git://github.com/jawnsy/Math-Random-ISAAC.git
version: 1.003
